{% set name = "libframe" %}
{% set version = "8.33" %}

package:
  name: {{ name }}
  version: {{version}}

source:
  fn: {{ name }}-{{version}}.tar.gz
  url: http://lappweb.in2p3.fr/virgo/FrameL/{{ name }}-{{version}}.tar.gz
  md5: 2163a812d1fa7b0a188b1720e1d9f181
  sha256: e06bff19c3b5ad797bceede2389bd0d11e66e44d84115637fb9e71cae404e7f3

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - automake
    - autoconf

test:
  commands:
    - FrChannels
    - FrCheck
    - FrCopy
    - FrDiff
    - FrDump
    - FrTrend

about:
  home: http://lappweb.in2p3.fr/virgo/FrameL/
  license: other
  license_file: LICENSE
  summary: LIGO/Virgo Frame Library

extra:
  recipe-maintainers:
    - duncanmmacleod
