{% set name = "libframe" %}
{% set version = "8.33" %}

package:
  name: {{ name }}
  version: {{version}}

source:
  fn: {{ name }}-{{version}}.tar.gz
  url: http://lappweb.in2p3.fr/virgo/FrameL/{{ name }}-{{version}}.tar.gz
  md5: 3ba410349f21dfc678498bb2e9f90707
  sha256: 7328d5aee815e9714b77c4440258f46a9b433fe84ccf8a7d3fc87614d2e87cf6

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}

test:
  commands:
    - FrChannels
    - FrCheck
    - FrCopy
    - FrDiff
    - FrDump
    - FrTrend

about:
  home: http://lappweb.in2p3.fr/virgo/FrameL/
  license: other
  license_file: LICENSE
  summary: LIGO/Virgo Frame Library

extra:
  recipe-maintainers:
    - duncanmmacleod
