{% set name = "libframe" %}
{% set version = "8.30" %}

package:
  name: {{ name }}
  version: {{version}}

source:
  url: http://lappweb.in2p3.fr/virgo/FrameL/{{ name }}-{{version}}.tar.gz
  sha256: 374743ccce835427a0900590a515c112661760e12ec596159d3f86073dd099da

build:
  number: 1001
  skip:  true  # [win]

requirements:
  build:
    - cmake
    - make  # [not win]
    - pkg-config  # [not win]
    - {{ compiler('c') }}

test:
  commands:
    - FrChannels
    - FrCheck
    - FrCopy
    - FrDiff
    - FrDump
    - FrTrend

about:
  home: http://lappweb.in2p3.fr/virgo/FrameL/
  license: other
  license_file: LICENSE
  summary: LIGO/Virgo Frame Library

extra:
  recipe-maintainers:
    - duncanmmacleod
