appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: OSt5ryKOOk6IQ6qAjbvploXS1G5vSh1OU9k/fjW32aYi8EcIgEFb6yV46mzEnuSSl+97Z7ovFdlf0jkxvPpPsK33DDAeRNFhNw5oNcJi3sGMLjENY2hf9nFAt6m32rhX54DIE01Hk9X0faW9AKnXJUAu1iJvMER81H0HS2EIrMnbl9mc5YzmkybpxxXHT9sycgrbiAALxVHzE89uMtJMxMsQVpkv9EGT/IwhF92IiphPVjcHAWP2yKndYTBkc8QHtcwrOD0SGYxM2jLfHdXyBFigmSP/wqnBWRHxIJGio/6E6BrTSPApMs6t6OXYMCj9vloSOcBLECTJBxuj2dif/mHI14pm1Im3X/Pf7t2Kyp3fObTY1kxBrZKKi61xlbffRcVrzDbipbLED7qUmDPIEqLmQmk+HiXf5JBUa6Xfk3+kBIOMPjLK3Gm7PTj6ud8/nHgPTGVlMzli5qsRSDkK+e5fskfXVvMNlALY/qIEQ/KD8pCthlmL84CHEcb/tEq1+8XZ9ZcU1RWBNTcgoom25UTbEL7619gIYssuWUFDObZ9I8Mmcv6HI/+lMyUjJ1NRcy78kV9uk8eD1fbex8emihSi1jaE+ITaQaHcG3CW/xYEu5RtSF/ligLRVDlBZGeKCEeRj+zrZdK5CyyeRvOXW7k2kN8C6Xi5zkSLxUIR8rY=}
